# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 366)
        MainWindow.setFixedSize(454, 366)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(160, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(100, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inputName.setFont(font)
        self.inputName.setText("")
        self.inputName.setObjectName("inputName")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(100, 270, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.URLInput = QtWidgets.QLineEdit(self.centralwidget)
        self.URLInput.setGeometry(QtCore.QRect(100, 230, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.URLInput.setFont(font)
        self.URLInput.setObjectName("URLInput")
        self.inputPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(100, 180, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inputPassword.setFont(font)
        self.inputPassword.setText("")
        self.inputPassword.setObjectName("inputPassword")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 70, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.errorText = QtWidgets.QLabel(self.centralwidget)
        self.errorText.setGeometry(QtCore.QRect(100, 310, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errorText.setFont(font)
        self.errorText.setStyleSheet("color: #7F0000;")
        self.errorText.setText("")
        self.errorText.setObjectName("errorText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.title.setText(_translate("MainWindow", "Авторизация"))
        self.inputName.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.loginButton.setText(_translate("MainWindow", "Далее"))
        self.URLInput.setText(_translate("MainWindow", "ws://127.0.0.1:4180"))
        self.URLInput.setPlaceholderText(_translate("MainWindow", "Сервер чата"))
        self.inputPassword.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Если аккаунт не существует, <br/>то будет создан новый</p></body></html>"))
