# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joinChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JoinChat(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 244)
        MainWindow.setFixedSize(452, 244)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("Вступить в чат")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setAccessibleName("")
        self.title.setAccessibleDescription("")
        self.title.setObjectName("title")
        self.inviteCode = QtWidgets.QLineEdit(self.centralwidget)
        self.inviteCode.setGeometry(QtCore.QRect(100, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inviteCode.setFont(font)
        self.inviteCode.setText("")
        self.inviteCode.setObjectName("inviteCode")
        self.joinButton = QtWidgets.QPushButton(self.centralwidget)
        self.joinButton.setGeometry(QtCore.QRect(100, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.joinButton.setFont(font)
        self.joinButton.setObjectName("joinButton")
        self.errorText = QtWidgets.QLabel(self.centralwidget)
        self.errorText.setGeometry(QtCore.QRect(100, 180, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errorText.setFont(font)
        self.errorText.setStyleSheet("color: red;")
        self.errorText.setText("")
        self.errorText.setObjectName("errorText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.title.setText(_translate("MainWindow", "Вступить в чат"))
        self.inviteCode.setPlaceholderText(_translate("MainWindow", "Инвайт-код"))
        self.joinButton.setText(_translate("MainWindow", "Вступить"))
